# Generated by Django 5.2.8 on 2025-11-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='О нашей кофейне', max_length=200, verbose_name='Заголовок')),
                ('history_title', models.CharField(default='Наша история', max_length=200, verbose_name='Заголовок истории')),
                ('history_text', models.TextField(default='История нашей кофейни...', verbose_name='Текст истории')),
                ('mission_title', models.CharField(default='Наша миссия', max_length=200, verbose_name='Заголовок миссии')),
                ('mission_text', models.TextField(default='Наша миссия...', verbose_name='Текст миссии')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Основное изображение')),
            ],
            options={
                'verbose_name': "Контент страницы 'О нас'",
                'verbose_name_plural': "Контент страницы 'О нас'",
            },
        ),
        migrations.CreateModel(
            name='ContactsPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='г. Москва, ул. Котикова, 15', verbose_name='Адрес')),
                ('phone', models.CharField(default='+7 (999) 123-45-67', max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(default='hello@cozycat.ru', max_length=254, verbose_name='Email')),
                ('work_hours', models.TextField(default='Пн-Пт: 8:00-22:00, Сб-Вс: 9:00-23:00', verbose_name='Часы работы')),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='contacts/', verbose_name='Изображение карты')),
            ],
            options={
                'verbose_name': 'Контент страницы контактов',
                'verbose_name_plural': 'Контент страницы контактов',
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Кофейня Уютный Котик', max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.TextField(default='Где кофе встречается с мурлыканием', verbose_name='Подзаголовок')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='homepage/', verbose_name='Главное изображение')),
                ('philosophy_title', models.CharField(default='Наша философия', max_length=200, verbose_name='Заголовок философии')),
                ('philosophy_text', models.TextField(default='Мы создали место, где можно насладиться кофе в компании котиков', verbose_name='Текст философии')),
                ('philosophy_image', models.ImageField(blank=True, null=True, upload_to='homepage/', verbose_name='Изображение философии')),
            ],
            options={
                'verbose_name': 'Контент главной страницы',
                'verbose_name_plural': 'Контент главной страницы',
            },
        ),
    ]
