# Generated by Django 5.2.8 on 2025-11-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_aboutpagecontent_contactspagecontent_homepagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя котика')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='cat_team/', verbose_name='Фото котика')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Член команды котиков',
                'verbose_name_plural': 'Команда котиков',
                'ordering': ['order'],
            },
        ),
    ]
