# Generated by Django 5.2.8 on 2025-11-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_catteammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Наше меню', max_length=200, verbose_name='Заголовок меню')),
                ('subtitle', models.TextField(default='Выберите свой любимый напиток', verbose_name='Подзаголовок меню')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='menu_page/', verbose_name='Главное фото меню')),
            ],
            options={
                'verbose_name': 'Контент страницы меню',
                'verbose_name_plural': 'Контент страницы меню',
            },
        ),
    ]
